"""
Discrete-event Named Data Networking (NDN) simulator.

Models the core NDN forwarding pipeline at a single monitored router R that sits
between a set of consumers/attackers and one producer:

    Interest arrives at R
        -> purge expired PIT entries          (timeouts == unsatisfied Interests)
        -> Content Store (CS) lookup           (cache HIT -> return Data now)
        -> PIT lookup                          (already pending -> aggregate)
        -> else insert PIT entry + forward     (FIB -> producer)
    Data arrives at R (from producer)
        -> insert into CS (LRU, capacity-bound)
        -> satisfy + remove the PIT entry

Two NDN-native attacks are modelled with their real mechanisms:

  * Interest Flooding: attacker emits Interests for UNSATISFIABLE names
    (not in the producer catalog). The producer never returns Data, so PIT
    entries linger until their lifetime expires -> the PIT is exhausted and the
    unsatisfied-Interest ratio spikes. This is the canonical PIT-exhaustion DoS.

  * Cache Pollution (locality disruption): attacker requests VALID but cold
    (unpopular) names uniformly at random across the catalog. These are
    satisfied and inserted into the CS, evicting the popular content that benign
    consumers rely on -> the Content Store hit ratio collapses.

Every Interest and Data packet crossing R is logged as an "observation" (one row
== one packet on the monitored link), together with the forwarder state at that
instant (PIT size, CS size, hit/miss, etc.). ndn_poc/features.py turns these
observation logs into 20-packet behavioural windows.

Pure-Python / NumPy only; deterministic given a seed for reproducibility.
"""
from __future__ import annotations

import heapq
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import numpy as np

# ── Packet / event kinds ────────────────────────────────────────────────────
INTEREST = "INTEREST"
DATA = "DATA"

# traffic source roles
BENIGN = "BENIGN"
INTEREST_FLOODING = "INTEREST_FLOODING"
CACHE_POLLUTION = "CACHE_POLLUTION"


@dataclass
class Observation:
    """One packet crossing the monitored router, with forwarder state snapshot."""
    t: float                # arrival time (s)
    kind: str               # INTEREST | DATA
    name: str               # content name
    src_role: str           # BENIGN | INTEREST_FLOODING | CACHE_POLLUTION | producer
    is_attack: int          # 1 if generated by an attacker source
    attack_type: str        # BENIGN | INTEREST_FLOODING | CACHE_POLLUTION
    cs_hit: int             # Interest satisfied from Content Store
    pit_aggregated: int     # Interest collapsed onto an existing PIT entry
    satisfiable: int        # 1 if name exists in producer catalog
    pit_size: int           # PIT occupancy right after handling this packet
    cs_size: int            # Content Store occupancy right after handling
    expired_since_last: int # PIT entries that timed out since previous packet
    rtt: float              # Data RTT (s) for DATA packets, else 0.0


@dataclass(order=True)
class _Event:
    t: float
    seq: int
    kind: str = field(compare=False)
    name: str = field(compare=False)
    src_role: str = field(compare=False)
    is_attack: int = field(compare=False)
    attack_type: str = field(compare=False)
    interest_time: float = field(compare=False, default=0.0)  # for RTT on DATA


class ContentStore:
    """Capacity-bounded LRU Content Store."""

    def __init__(self, capacity: int):
        self.capacity = capacity
        self._store: "Dict[str, None]" = {}  # ordered dict as LRU

    def __contains__(self, name: str) -> bool:
        return name in self._store

    def get(self, name: str) -> bool:
        if name in self._store:
            self._store.pop(name)
            self._store[name] = None  # move to MRU
            return True
        return False

    def put(self, name: str) -> None:
        if name in self._store:
            self._store.pop(name)
        elif len(self._store) >= self.capacity:
            # evict least-recently-used (first key)
            self._store.pop(next(iter(self._store)))
        self._store[name] = None

    def __len__(self) -> int:
        return len(self._store)


class PIT:
    """Pending Interest Table with per-entry lifetime (for timeout accounting)."""

    def __init__(self, lifetime: float):
        self.lifetime = lifetime
        self._entries: Dict[str, Tuple[float, int]] = {}  # name -> (expiry, count)

    def __contains__(self, name: str) -> bool:
        return name in self._entries

    def add_or_aggregate(self, name: str, now: float) -> bool:
        """Returns True if aggregated onto an existing entry, False if new."""
        if name in self._entries:
            expiry, count = self._entries[name]
            self._entries[name] = (expiry, count + 1)
            return True
        self._entries[name] = (now + self.lifetime, 1)
        return False

    def satisfy(self, name: str) -> None:
        self._entries.pop(name, None)

    def purge_expired(self, now: float) -> int:
        """Remove entries whose lifetime elapsed. Returns count purged (timeouts)."""
        expired = [n for n, (exp, _) in self._entries.items() if exp <= now]
        for n in expired:
            self._entries.pop(n, None)
        return len(expired)

    def __len__(self) -> int:
        return len(self._entries)


@dataclass
class EpisodeConfig:
    duration: float = 6.0
    seed: int = 0
    # producer / content
    catalog_size: int = 500
    zipf_s: float = 1.1
    producer_delay_lo: float = 0.005
    producer_delay_hi: float = 0.020
    # router state
    cs_capacity: int = 100
    pit_lifetime: float = 2.0
    # benign consumers
    n_benign: int = 4
    benign_rate_lo: float = 20.0
    benign_rate_hi: float = 40.0
    # attack
    attack_type: str = BENIGN         # BENIGN | INTEREST_FLOODING | CACHE_POLLUTION
    attack_start: float = 1.0         # warmup before attacker turns on
    n_attackers: int = 1
    attack_rate_lo: float = 150.0
    attack_rate_hi: float = 350.0


def _poisson_arrivals(rng: np.random.Generator, rate: float, t0: float, t1: float) -> List[float]:
    """Homogeneous Poisson arrival times in [t0, t1)."""
    times = []
    t = t0
    if rate <= 0:
        return times
    while True:
        t += rng.exponential(1.0 / rate)
        if t >= t1:
            break
        times.append(t)
    return times


def _zipf_ranks(rng: np.random.Generator, n: int, size: int, s: float) -> np.ndarray:
    """Sample `size` content ids from a Zipf(s) popularity over `n` items."""
    ranks = np.arange(1, n + 1)
    weights = 1.0 / np.power(ranks, s)
    weights /= weights.sum()
    return rng.choice(n, size=size, p=weights)


def run_episode(cfg: EpisodeConfig) -> List[Observation]:
    """Run one simulation episode; return the ordered observation log."""
    rng = np.random.default_rng(cfg.seed)
    cs = ContentStore(cfg.cs_capacity)
    pit = PIT(cfg.pit_lifetime)

    catalog = {f"/prod/obj/{i}" for i in range(cfg.catalog_size)}

    heap: List[_Event] = []
    seq = 0

    def push(ev_t, kind, name, role, is_atk, atk_type, interest_time=0.0):
        nonlocal seq
        heapq.heappush(heap, _Event(ev_t, seq, kind, name, role, is_atk, atk_type, interest_time))
        seq += 1

    # ── schedule benign consumer Interests (Zipf-popular, satisfiable) ──
    for _ in range(cfg.n_benign):
        rate = rng.uniform(cfg.benign_rate_lo, cfg.benign_rate_hi)
        times = _poisson_arrivals(rng, rate, 0.0, cfg.duration)
        ids = _zipf_ranks(rng, cfg.catalog_size, len(times), cfg.zipf_s)
        for ti, cid in zip(times, ids):
            push(ti, INTEREST, f"/prod/obj/{int(cid)}", BENIGN, 0, BENIGN)

    # ── schedule attacker Interests ──
    if cfg.attack_type == INTEREST_FLOODING:
        for a in range(cfg.n_attackers):
            rate = rng.uniform(cfg.attack_rate_lo, cfg.attack_rate_hi)
            times = _poisson_arrivals(rng, rate, cfg.attack_start, cfg.duration)
            for ti in times:
                # unsatisfiable, unique names -> PIT never cleared until timeout
                uid = rng.integers(0, 2**31)
                push(ti, INTEREST, f"/prod/attack/{a}/{uid}", INTEREST_FLOODING, 1, INTEREST_FLOODING)
    elif cfg.attack_type == CACHE_POLLUTION:
        for _ in range(cfg.n_attackers):
            rate = rng.uniform(cfg.attack_rate_lo, cfg.attack_rate_hi)
            times = _poisson_arrivals(rng, rate, cfg.attack_start, cfg.duration)
            for ti in times:
                # valid but uniformly-random (mostly cold) names -> evict popular
                cid = rng.integers(0, cfg.catalog_size)
                push(ti, INTEREST, f"/prod/obj/{int(cid)}", CACHE_POLLUTION, 1, CACHE_POLLUTION)

    # ── event loop ──
    log: List[Observation] = []
    last_t = 0.0
    while heap:
        ev = heapq.heappop(heap)
        now = ev.t
        expired = pit.purge_expired(now)

        if ev.kind == INTEREST:
            satisfiable = int(ev.name in catalog)
            cs_hit = 0
            aggregated = 0
            if cs.get(ev.name):
                cs_hit = 1
                # CS hit: return Data immediately (observed as a DATA packet)
                delay = rng.uniform(cfg.producer_delay_lo, cfg.producer_delay_hi) * 0.1
                push(now + delay, DATA, ev.name, "producer", ev.is_attack, ev.attack_type, now)
            else:
                aggregated = int(pit.add_or_aggregate(ev.name, now))
                if not aggregated and satisfiable:
                    # forward to producer; Data returns after link+proc delay
                    delay = rng.uniform(cfg.producer_delay_lo, cfg.producer_delay_hi)
                    push(now + delay, DATA, ev.name, "producer", ev.is_attack, ev.attack_type, now)
                # if not satisfiable (flooding): no Data ever -> entry times out later

            log.append(Observation(
                t=now, kind=INTEREST, name=ev.name, src_role=ev.src_role,
                is_attack=ev.is_attack, attack_type=ev.attack_type,
                cs_hit=cs_hit, pit_aggregated=aggregated, satisfiable=satisfiable,
                pit_size=len(pit), cs_size=len(cs), expired_since_last=expired, rtt=0.0,
            ))
        else:  # DATA
            pit.satisfy(ev.name)
            cs.put(ev.name)
            log.append(Observation(
                t=now, kind=DATA, name=ev.name, src_role=ev.src_role,
                is_attack=ev.is_attack, attack_type=ev.attack_type,
                cs_hit=0, pit_aggregated=0, satisfiable=1,
                pit_size=len(pit), cs_size=len(cs), expired_since_last=expired,
                rtt=max(0.0, now - ev.interest_time),
            ))
        last_t = now

    return log
